# Generated by Django 4.0.4 on 2022-04-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('exe', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
    ]
