# Generated by Django 4.0.4 on 2022-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth',
            name='exe',
            field=models.CharField(max_length=100),
        ),
    ]
